name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: build
        env:
          BAIDU_HM_CODE: ${{ secrets.BAIDU_HM_CODE }}
        run: pnpm build
      - name: deploy
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: dist
          remote_path: /
          clean: true
